// Replace with the deployed address from deployments/sepolia/HushOracle.json
export const CONTRACT_ADDRESS = '0xCFc20140Cb9E48de104200AeE8bC98607711241E';

export const CONTRACT_ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'AlreadyClaimed', type: 'error' },
  { inputs: [], name: 'AlreadyPredicted', type: 'error' },
  { inputs: [], name: 'InvalidToken', type: 'error' },
  { inputs: [], name: 'MissingPrediction', type: 'error' },
  { inputs: [], name: 'MissingPrice', type: 'error' },
  { inputs: [], name: 'PriceAlreadySet', type: 'error' },
  { inputs: [], name: 'StakeRequired', type: 'error' },
  { inputs: [], name: 'StakeTooLarge', type: 'error' },
  { inputs: [], name: 'TooEarly', type: 'error' },
  { inputs: [], name: 'Unauthorized', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'day', type: 'uint256' },
      { indexed: false, internalType: 'uint64', name: 'ethPrice', type: 'uint64' },
      { indexed: false, internalType: 'uint64', name: 'btcPrice', type: 'uint64' },
    ],
    name: 'DailyPriceUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint8', name: 'token', type: 'uint8' },
      { indexed: true, internalType: 'uint256', name: 'day', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'stake', type: 'uint256' },
    ],
    name: 'PredictionPlaced',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint8', name: 'token', type: 'uint8' },
      { indexed: true, internalType: 'uint256', name: 'day', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'stake', type: 'uint256' },
    ],
    name: 'PredictionConfirmed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'uint8', name: 'token', type: 'uint8' },
      { internalType: 'uint256', name: 'day', type: 'uint256' },
    ],
    name: 'confirmPrediction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentDay',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'day', type: 'uint256' }],
    name: 'getDailyPrice',
    outputs: [
      { internalType: 'uint64', name: 'ethPrice', type: 'uint64' },
      { internalType: 'uint64', name: 'btcPrice', type: 'uint64' },
      { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLatestDay',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint8', name: 'token', type: 'uint8' },
      { internalType: 'uint256', name: 'day', type: 'uint256' },
    ],
    name: 'getPrediction',
    outputs: [
      { internalType: 'euint64', name: 'price', type: 'bytes32' },
      { internalType: 'euint8', name: 'direction', type: 'bytes32' },
      { internalType: 'uint256', name: 'stake', type: 'uint256' },
      { internalType: 'bool', name: 'claimed', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getUserPoints',
    outputs: [{ internalType: 'euint64', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'latestRecordedDay',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint8', name: 'token', type: 'uint8' },
      { internalType: 'externalEuint64', name: 'encryptedPrice', type: 'bytes32' },
      { internalType: 'externalEuint8', name: 'encryptedDirection', type: 'bytes32' },
      { internalType: 'bytes', name: 'inputProof', type: 'bytes' },
    ],
    name: 'placePrediction',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint64', name: 'ethPrice', type: 'uint64' },
      { internalType: 'uint64', name: 'btcPrice', type: 'uint64' },
    ],
    name: 'updateDailyPrices',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
